### ISSUE TITLE
Automate the push from github to gitlab

### ISSUE THREAD

**Issue by colleenskemp** [accessibility-in-action/platform#1721]
It would be ideal to include this as part of the Kube transition. The goal is to have mirroring repositories. See notes here for greater context: https://colabcoop.atlassian.net/wiki/spaces/IRIS/blog/2023/05/09/2615115777/IRIS+Full+Team+Sync+Release+Planning+May+2023

@JureUrsic - you communicated during the meeting that more research would be needed for this item. Can you also please estimate?

**Comment by michelled** [comment]
Now that the new dev site is up, this is a very high priority task.

**Comment by marvinroman** [comment]
So research showed that mirror **Pull** is a premium feature on Gitlab.
Here is the easiest solution.

Add the following git hook into your repository. `.git/hooks/post-commit`.

```bash
#!/bin/sh

# Function to check if the current branch is in the list
is_selected_branch() {
  local branch
  for branch in "${selected_branches[@]}"; do
    [[ "$branch" == "$current_branch" ]] && return 0
  done
  return 1
}

# Define the selected branches
selected_branches=("production" "dev" "staging")

# Get the current branch
current_branch=$(git symbolic-ref --short HEAD)

# Check if the current branch is in the selected branches list and the remote name is 'origin'
if is_selected_branch; then
  echo "Pushing branch '$current_branch' to 'kube' remote..."
  git push kube "$current_branch"
fi

exit 0
```

This will deploy the code to the **kube** remote when the user commits to the **dev**, **staging**, or **production** branch.

**Comment by jobara** [comment]
@marvinroman A few thoughts:

- Can we use GitHub actions that are triggered on merges to the relevant branches?
- In GitHub "dev" is the primary branch; however GitLab uses a 'development' branch for the dev deploy. At the moment we've mirrored this to have a 'development' branch in GitHub but I'd like to remove that and just have the 'dev' branch from GitHub push to the 'development' branch in GitLab.
- The GitHub actions should only run from this repository. Not for example from my fork of the repo. You can add a check in the GitHub action to make sure it only runs in the correct repo.
- Do we also want to push tags to GitLab. I don't think they are necessary for any deployments, but is it something that we'd want there as well?

I did a quick search and found '[Mirror to GitLab and trigger GitLab CI](https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci)' GitHub action which sounds like it would do what we want. Although you'll want to review it to make sure it does, and that the codebase is good. Another option where you'd write your own GitHub action such as https://stackoverflow.com/questions/63308904/push-to-gitlab-with-access-token-using-github-actions. Again, that's just an example there may be better ways of doing that.

**Comment by marvinroman** [comment]
I have tested the following to mirror a fork to gitlab.

There are a few setup steps.
1. Create an SSH key for the mirroring and:  
-  Add the public key into Gitlab **Deploy Keys** with **write access**.  
- Add the private key with the name `GITLAB_SSH_KEY` to Github **Secrets** on the repository.  
2. Add the following Github **Variables**. **GIT_USER**, **GIT_EMAIL**, **GITLAB_URL**  

Action workflow `.github/workflows/mirror-to-gitlab.yml`.  

```yaml
name: Mirror branches to GitLab

on:
  push:
    branches:
      - dev
      - staging
      - production

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ vars.GIT_USER }}"
          git config --global user.email "${{ vars.GIT_EMAIL }}"
          git remote add gitlab ${{ vars.GITLAB_URL }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Push to GitLab - Development branch
        if: github.ref == 'refs/heads/dev'
        run: |
          git push gitlab HEAD:development

      - name: Push to GitLab - Staging branch
        if: github.ref == 'refs/heads/staging'
        run: |
          git push gitlab HEAD:staging

      - name: Push to GitLab - Production branch
        if: github.ref == 'refs/heads/production'
        run: |
          git push gitlab HEAD:production
```

I don't have access to add secrets or variables to the repository. So I will need somebody with proper access to finish those steps before the workflow can be released.
